# Generated by Django 2.2.6 on 2019-11-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('Name',)},
        ),
    ]
