# Generated by Django 2.2.6 on 2019-11-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractworkers',
            name='emergency_contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contractworkers',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='emergency_contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='humanresource',
            name='emergency_contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='humanresource',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ict',
            name='emergency_contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ict',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='emergency_contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='emergency_contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
