# Generated by Django 2.2.6 on 2019-11-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('next_of_kin', models.CharField(max_length=100)),
                ('phone_number_next_of_kin', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
